"""initial schema

Revision ID: 389c613ffdae
Revises: 
Create Date: 2026-05-04 22:45:37.364152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '389c613ffdae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('conference', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_team_score', sa.Integer(), nullable=True),
    sa.Column('away_team_score', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('postseason', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('height_feet', sa.Integer(), nullable=True),
    sa.Column('height_inches', sa.Integer(), nullable=True),
    sa.Column('weight_pounds', sa.Integer(), nullable=True),
    sa.Column('draft_year', sa.Integer(), nullable=True),
    sa.Column('draft_round', sa.Integer(), nullable=True),
    sa.Column('draft_number', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('doc_type', sa.String(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('min', sa.String(), nullable=True),
    sa.Column('pts', sa.Integer(), nullable=True),
    sa.Column('reb', sa.Integer(), nullable=True),
    sa.Column('ast', sa.Integer(), nullable=True),
    sa.Column('stl', sa.Integer(), nullable=True),
    sa.Column('blk', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('fg3m', sa.Integer(), nullable=True),
    sa.Column('fg3a', sa.Integer(), nullable=True),
    sa.Column('fg3_pct', sa.Float(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.Column('oreb', sa.Integer(), nullable=True),
    sa.Column('dreb', sa.Integer(), nullable=True),
    sa.Column('turnover', sa.Integer(), nullable=True),
    sa.Column('pf', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season_averages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('pts', sa.Float(), nullable=True),
    sa.Column('reb', sa.Float(), nullable=True),
    sa.Column('ast', sa.Float(), nullable=True),
    sa.Column('stl', sa.Float(), nullable=True),
    sa.Column('blk', sa.Float(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('fg3_pct', sa.Float(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('season_averages')
    op.drop_table('player_game_stats')
    op.drop_table('documents')
    op.drop_table('players')
    op.drop_table('messages')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('conversations')
    # ### end Alembic commands ###
