"""update schema to match actual api fields

Revision ID: 3d832b85677f
Revises: 66f20696d1e5
Create Date: 2026-05-05 22:35:44.270266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d832b85677f'
down_revision: Union[str, Sequence[str], None] = '66f20696d1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('players', 'draft_number')
    op.drop_column('players', 'weight_pounds')
    op.drop_column('players', 'height_inches')
    op.drop_column('players', 'height_feet')
    op.drop_column('players', 'draft_round')
    op.drop_column('players', 'position')
    op.drop_column('players', 'draft_year')
    op.add_column('teams', sa.Column('nickname', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('state', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('year_founded', sa.Integer(), nullable=True))
    op.drop_column('teams', 'conference')
    op.drop_column('teams', 'division')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('division', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('conference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('teams', 'year_founded')
    op.drop_column('teams', 'state')
    op.drop_column('teams', 'nickname')
    op.add_column('players', sa.Column('draft_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('draft_round', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('height_feet', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('height_inches', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('weight_pounds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('draft_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('players', 'is_active')
    op.drop_column('players', 'full_name')
    # ### end Alembic commands ###
