"""add game team stats column

Revision ID: e8981e51af15
Revises: 3d832b85677f
Create Date: 2026-05-14 01:54:39.491370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8981e51af15'
down_revision: Union[str, Sequence[str], None] = '3d832b85677f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('home_team_wins', sa.Boolean(), nullable=True))
    op.add_column('games', sa.Column('home_team_fg_pct', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('away_team_fg_pct', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('home_team_fg3_pct', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('away_team_fg3_pct', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('home_team_reb', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_team_reb', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_team_ast', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_team_ast', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_team_tov', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_team_tov', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_team_stl', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_team_stl', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_team_blk', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_team_blk', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'away_team_blk')
    op.drop_column('games', 'home_team_blk')
    op.drop_column('games', 'away_team_stl')
    op.drop_column('games', 'home_team_stl')
    op.drop_column('games', 'away_team_tov')
    op.drop_column('games', 'home_team_tov')
    op.drop_column('games', 'away_team_ast')
    op.drop_column('games', 'home_team_ast')
    op.drop_column('games', 'away_team_reb')
    op.drop_column('games', 'home_team_reb')
    op.drop_column('games', 'away_team_fg3_pct')
    op.drop_column('games', 'home_team_fg3_pct')
    op.drop_column('games', 'away_team_fg_pct')
    op.drop_column('games', 'home_team_fg_pct')
    op.drop_column('games', 'home_team_wins')
    # ### end Alembic commands ###
